BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Albums" (
	"Album_ID"	INTEGER,
	"Artist_ID"	INTEGER,
	"Title"	TEXT NOT NULL,
	"Location"	TEXT NOT NULL,
	PRIMARY KEY("Album_ID"),
	FOREIGN KEY("Artist_ID") REFERENCES "Artists"("Artist_ID") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "Songs" (
	"Song_ID"	INTEGER,
	"Album_ID"	INTEGER NOT NULL,
	"Title"	TEXT NOT NULL,
	PRIMARY KEY("Song_ID"),
	FOREIGN KEY("Album_ID") REFERENCES "Albums"("Album_ID") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "Artists" (
	"Artist_ID"	INTEGER,
	"Name"	TEXT NOT NULL,
	PRIMARY KEY("Artist_ID")
);
COMMIT;
